### ISSUE TITLE
Messages won't send.

### ISSUE THREAD

**Issue by shahzeb1** [totaljs/premium-messenger#2]
Hello,

So I just got Total.js Messenger installed on my computer. Exciting stuff.

## The Problem:

(Seemingly randomly) messages don't send. I type in a message and press `<enter>`. The input field clears, but the a) message does not appear on the web UI **and** b) the message does not appear in any of the database .json files.

I'm not exactly sure where in the pipeline this error is happening. I tried debugging it, but this issue seems to come seemingly randomly.

#### Update:
Even adding a listener for when the messages are sent (`F.on('messenger.message', function(controller, client, message) {...}`) is not getting triggered.

**Comment by petersirka** [comment]
Hi @shahzeb1 
can you write me on messenger.totaljs.com? I need to see it, we can use TeamViewer if you agree.

Thank you
